name: labs
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  checked_yaml: ^2.0.1
  io: ^1.0.3
  json_annotation: ^4.8.0
  logging: ^1.0.2
  path: ^1.8.0
  flutter:
    sdk: flutter
  provider: ^6.0.5
  english_words: ^4.0.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  lints: ^2.0.0
  test: ^1.16.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
